### ISSUE TITLE
Is it legal?

### ISSUE THREAD

**Issue by karaketir16** [Asocia/enroll-itu#1]

**Comment by sahinakkaya** [comment]
It is legal for sure. At the end of the day, it is just sending a POST request to some API which is what your browser does when you press "Submit" button. 

Actually, the browser does **MORE** than that. It requests hell lot of files to show you a properly formatted web page. Look at all these requests... 

![2022-02-18_00-00](https://user-images.githubusercontent.com/32161460/154570119-16af11ef-7159-4d89-8b4e-b4b3dd208fb9.png)

You wouldn't send that many requests if you use this script. Use this script and reduce the load on ITU's servers 🤘

**Comment by sahinakkaya** [comment]
To any arguments against running it as a cronjob: If you don't abuse it, it shouldn't be a problem. If you think one should have right to send one request per minute (rpm), then use it. If you think it is too much make it 1/2 rpm, maybe even 1/10 rpm? 


If you abuse it, of course you may be punished. This is also the case when you use browser :slightly_smiling_face:

**Comment by karaketir16** [comment]
I wonder Authorization header is working on just that IP or this header can be used on anywhere? If there is no IP check on server side, I can create an web interface that runs that script at background. ( Sharing or not Sharing Authorization header is user's responsibility :) )

**Comment by sahinakkaya** [comment]
The token here is Json Web Token (JWT) and it contains some information to identify you. I don't think there is an IP check because that would mean the site would log you out if you connect to a different network while logged in. I didn't see this behaviour anywhere.
